# Generated by Django 6.0.3 on 2026-03-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NearEarthObject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('diameter_min', models.FloatField()),
                ('diameter_max', models.FloatField()),
                ('is_potentially_hazardous', models.BooleanField()),
            ],
        ),
    ]
