# Generated by Django 6.0.3 on 2026-03-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPdf',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='pdfs/%Y/%m/%d/')),
                ('uploaded_by', models.CharField(max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_name', models.CharField(max_length=255)),
            ],
        ),
    ]
