# Generated by Django 6.0.3 on 2026-03-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_uploadedpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
