# Generated by Django 6.0.3 on 2026-03-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_uploadedpdf_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedPdf',
        ),
    ]
